version: '3'

networks:
  network:

services:
  web-server:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}.nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - network

  database:
    image: mysql:5.7.29
    container_name: ${APP_NAME}.database
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - network

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: ${APP_NAME}.php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - network
